[package]
name = "tan00"
version = "0.1.0"
authors = ["Michael Angerman <stormasm@gmail.com>"]
edition = "2018"

[dependencies]
tantivy = "0.11.3"
tempfile = "3.0"
serde_json = "1.0"
crossbeam = "0.7"
